# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "metro-workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "whoishebtw"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "Obsidan 24"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-windows'></i> Blog Homepage"
identifier = "Back En"
url = "/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> See the site's source"
identifier = "GH En"
url = "https://github.com/LongKira-Obsidian24"
weight = 21

[Languages.vi]
title = "Obsidian 24"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-windows'></i>Trang chủ Blog"
identifier = "GH Vi"
url = "https://github.com/LongKira-Obsidian24"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Xem mã nguồn website này"
identifier = "Back Vi"
url = "/vi"
weight = 21

[markup.goldmark.renderer]
  unsafe = true

# [security]
#   enableInlineShortcodes = true
